Add events for image uploads
advoor/nova-editor-js pull request #98
Opened 2023-05-25 21:22 UTC by Woeler

This PR adds events for image uploads and thumbnail generation. This allows users to hook into these processes. I for instance want to convert uploaded images to webp, and use the OG image as fallback. With these events I can now just listen for uploads and dispatch conversion jobs.

I'm sure there are many other things people will be able to do with this feature.

2023-07-12 18:30 UTC, roelofr requested changes

2023-07-12 19:08 UTC, roelofr commented on .gitignore
> +/.ddev/
What are these files for, they seem unused.

If it's something you need to ignore locally, please add them to either a [global ignore file][1] or in the `.git/info/exclude` file in your repository.

[1]: https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

2023-07-13 07:45 UTC, Woeler commented
Thanks for your comments. I will update this pr this week!

2023-07-19 19:35 UTC, Woeler commented
I am unsure why the v8 tests keep failing. Running them locally produces no such errors.

2023-11-21 09:42 UTC, Woeler commented
@roelofr Alright, everything seems to be good now

2023-11-24 01:00 UTC, roelofr requested changes
Hey, thanks for picking this back up after the pipelines were fixed.

As time moves on, so does my understanding of code, It seems like a good idea to remove unused traits, but other than that it looks ready to roll.

Please add a CHANGELOG entry so we can keep track of these changes, then we'll get this merged in.

2023-12-13 12:21 UTC, roelofr approved these changes

2023-12-13 12:21 UTC, merged